In [5]:
import pandas as pd

In [6]:
genophi_interaction_matrix = pd.read_csv("/Users/Farzaneh/Documents/phage-bacteria-interaction/GenoPHI/data/interation_matrices/ecoli_interaction_matrix.csv")
our_interaction_matrix = pd.read_csv("/Users/Farzaneh/Documents/phage-bacteria-interaction/phage_interactions/data/multi_source_data_v3/interaction_table.csv")

In [7]:
genophi_interaction_matrix.sort_values(by='strain', inplace=True)
genophi_interaction_matrix

       strain     phage  interaction
17019  001023    427_P3            0
27873  001023   LI10_P6            1
33903  001023   LM08_P2            1
21843  001023    409_P5            0
135    001023  55989_P2            1
...       ...       ...          ...
20578  VDG427   LM33_P1            0
35854  VDG427    411_P2            0
18166  VDG427   AN17_P1            0
15754  VDG427  NAN33_P6            0
76     VDG427  55989_P2            0

[37788 rows x 3 columns]

In [ ]:
our_interaction_matrix.loc[our_interaction_matrix['source'] == 'coli_phage_interactions_2023']
coli_phage_interactions_2023 = our_interaction_matrix.loc[our_interaction_matrix['source'] == 'coli_phage_interactions_2023'].copy()
coli_phage_interactions_2023.rename(columns={'bacteria': 'strain'}, inplace=True)

/var/folders/kg/2ccp8g2970l38jw3n3v4bnnw0000gp/T/ipykernel_4268/2092848926.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coli_phage_interactions_2023.rename(columns={'bacteria': 'strain'}, inplace=True)

In [11]:
coli_phage_interactions_2023['strain'] = coli_phage_interactions_2023['strain'].str.replace('-', '')
coli_phage_interactions_2023['strain'] = coli_phage_interactions_2023['strain'].str.replace('_', '')
coli_phage_interactions_2023['strain'] = coli_phage_interactions_2023['strain'].str.upper()
coli_phage_interactions_2023.sort_values(by='strain', inplace=True)
coli_phage_interactions_2023

/var/folders/kg/2ccp8g2970l38jw3n3v4bnnw0000gp/T/ipykernel_4268/3616535925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coli_phage_interactions_2023['strain'] = coli_phage_interactions_2023['strain'].str.replace('-', '')
/var/folders/kg/2ccp8g2970l38jw3n3v4bnnw0000gp/T/ipykernel_4268/3616535925.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coli_phage_interactions_2023['strain'] = coli_phage_interactions_2023['strain'].str.replace('_', '')
/var/folders/kg/2ccp8g2970l38jw3n3v4bnnw0000gp/T/ipykernel_4268/3616535925.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coli_phage_interactions_2023['strain'] = coli_phage_interactions_2023['strain'].str.upper()
/var/folders/kg/2ccp8g2970l38jw3n3v4bnnw0000gp/T/ipykernel_4268/3616535925.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coli_phage_interactions_2023.sort_values(by='strain', inplace=True)

       strain      phage  interaction                        source
12922  001023    LF73_P3          0.0  coli_phage_interactions_2023
12946  001023    LF31_P3          0.0  coli_phage_interactions_2023
12945  001023    LM33_P1          1.0  coli_phage_interactions_2023
12944  001023    LI10_P2          1.0  coli_phage_interactions_2023
12943  001023    LI10_P1          2.0  coli_phage_interactions_2023
...       ...        ...          ...                           ...
7329   VDG427    LI10_P6          0.0  coli_phage_interactions_2023
7330   VDG427   NIC06_P3          0.0  coli_phage_interactions_2023
7331   VDG427     412_P1          0.0  coli_phage_interactions_2023
7322   VDG427     423_P9          0.0  coli_phage_interactions_2023
7263   VDG427  BCH953_P2          2.0  coli_phage_interactions_2023

[38435 rows x 4 columns]

In [12]:
merged_matrix = pd.merge(
    coli_phage_interactions_2023,
    genophi_interaction_matrix,
    on=['strain', 'phage'],
    how='outer',
    suffixes=('_coli', '_genophi')
)
merged_matrix

,strain,phage,interaction_coli,source,interaction_genophi
0,001023,409_P1,NaN,NaN,0.0
1,001023,409_P3,NaN,NaN,0.0
2,001023,409_P5,NaN,NaN,0.0
3,001023,409_P6,NaN,NaN,0.0
4,001023,409_P8,NaN,NaN,0.0
...,...,...,...,...,...
38586,VDG427,NRG_11A2,NaN,NaN,0.0
38587,VDG427,NRG_11B1,0.0,coli_phage_interactions_2023,0.0
38588,VDG427,NRG_12A1B,0.0,coli_phage_interactions_2023,0.0
38589,VDG427,T4LD,0.0,coli_phage_interactions_2023,NaN
38590,VDG427,T7_Portugal,0.0,coli_phage_interactions_2023,NaN

In [15]:
# Show rows in merged_matrix with at least one null value in any column
contain_null = merged_matrix[merged_matrix.isnull().any(axis=1)]
print("Number of unique strains (bacteria):", merged_matrix['strain'].nunique())
print("Number of unique phages:", merged_matrix['phage'].nunique())
# Show counts for each phage (how many rows for each phage)
print("Phage occurrence counts (merged_matrix):")
print(merged_matrix['phage'].value_counts())
print("\nBacteria occurrence counts (merged_matrix):")
print(merged_matrix['strain'].value_counts())

Number of unique strains (bacteria): 402
Number of unique phages: 96
Phage occurrence counts (merged_matrix):
phage
409_P1      402
409_P3      402
LI10_P2     402
LI10_P1     402
LF82_P9     402
           ...
55989_P2    402
55989_P1    402
536_P9      402
536_P7      402
T4LD        401
Name: count, Length: 96, dtype: int64

Bacteria occurrence counts (merged_matrix):
strain
IAI24     96
LI10      96
NIC06     96
NAN33     96
MT1B1     96
          ..
H009      96
FNB9      96
FNB7      96
FNB4      96
001023    95
Name: count, Length: 402, dtype: int64

In [21]:
# Compare phages present in coli_phage_interactions_2023 and genophi_interaction_matrix
phages_coli_2023 = set(coli_phage_interactions_2023['phage'].unique())
phages_genophi = set(genophi_interaction_matrix['phage'].unique())

phages_only_in_coli_2023 = phages_coli_2023 - phages_genophi
phages_only_in_genophi = phages_genophi - phages_coli_2023

print("Phages only in coli_phage_interactions_2023 (not in genophi):")
print(sorted(phages_only_in_coli_2023))
print(f"Total: {len(phages_only_in_coli_2023)}")

print("\nPhages only in genophi_interaction_matrix (not in coli_phage_interactions_2023):")
print(sorted(phages_only_in_genophi))
print(f"Total: {len(phages_only_in_genophi)}")

Phages only in coli_phage_interactions_2023 (not in genophi):
['T4LD', 'T7_Portugal']
Total: 2

Phages only in genophi_interaction_matrix (not in coli_phage_interactions_2023):
[]
Total: 0

In [23]:
# Compare strains present in coli_strain_interactions_2023 and genophi_interaction_matrix
strains_coli_2023 = set(coli_phage_interactions_2023['strain'].unique())
print(len(strains_coli_2023))
strains_genophi = set(genophi_interaction_matrix['strain'].unique())
print(len(strains_genophi))

strains_only_in_coli_2023 = strains_coli_2023 - strains_genophi
strains_only_in_genophi = strains_genophi - strains_coli_2023

strains_common = strains_coli_2023 & strains_genophi
print(len(strains_common))

print("strains only in coli_phage_interactions_2023 (not in genophi):")
print(sorted(strains_only_in_coli_2023))
print(f"Total: {len(strains_only_in_coli_2023)}")

print("\nstrains only in genophi_interaction_matrix (not in coli_phage_interactions_2023):")
print(sorted(strains_only_in_genophi))
print(f"Total: {len(strains_only_in_genophi)}")

402
402
402
strains only in coli_phage_interactions_2023 (not in genophi):
[]
Total: 0

strains only in genophi_interaction_matrix (not in coli_phage_interactions_2023):
[]
Total: 0

In [29]:
coli_phage_interactions_2023.reset_index(drop=True, inplace=True)
coli_phage_interactions_2023['interaction'] = coli_phage_interactions_2023['interaction'].apply(lambda x: 0 if (x == 0 or x == '0.0') else 1)
coli_phage_interactions_2023.drop(columns=['source'], inplace=True)

/var/folders/kg/2ccp8g2970l38jw3n3v4bnnw0000gp/T/ipykernel_4268/126838517.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coli_phage_interactions_2023['interaction'] = coli_phage_interactions_2023['interaction'].apply(lambda x: 0 if (x == 0 or x == '0.0') else 1)
/var/folders/kg/2ccp8g2970l38jw3n3v4bnnw0000gp/T/ipykernel_4268/126838517.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coli_phage_interactions_2023.drop(columns=['source'], inplace=True)

In [31]:
outer_merged_matrix = pd.merge(
    coli_phage_interactions_2023,
    genophi_interaction_matrix,
    on=['strain', 'phage'],
    how='outer',
    suffixes=('_coli', '_genophi')
)
print(outer_merged_matrix.shape)
inner_merged_matrix = pd.merge(
    coli_phage_interactions_2023,
    genophi_interaction_matrix,
    on=['strain', 'phage'],
    how='inner',
    suffixes=('_coli', '_genophi')
)
inner_merged_matrix

print(inner_merged_matrix.shape)

# Check if interaction_coli and interaction_genophi are the same in the inner merge
comparison = inner_merged_matrix[['interaction_coli', 'interaction_genophi']].copy()

# Remove rows where either value is missing (to focus on common measurements)
comparison = comparison.dropna(subset=['interaction_coli', 'interaction_genophi'])

# See how many are the same (==, as floats or ints)
same = (comparison['interaction_coli'] == comparison['interaction_genophi'])

num_same = same.sum()
num_total = len(same)

print(f"Number of matching interactions: {num_same} out of {num_total} ({num_same/num_total:.2%})")
print(f"Number of non-matching interactions: {num_total - num_same}")

# Optionally, show non-matching examples:
print("\nExamples of mismatched interactions:")
mismatched = comparison[~same]
print(mismatched.head(10))

(38591, 4)
(37632, 4)
Number of matching interactions: 37632 out of 37632 (100.00%)
Number of non-matching interactions: 0

Examples of mismatched interactions:
Empty DataFrame
Columns: [interaction_coli, interaction_genophi]
Index: []

In [32]:
coli_phage_interactions_2023.to_csv("/Users/Farzaneh/Documents/phage-bacteria-interaction/Raw_data/coli_interaction_table.csv", index=False)

In [ ]:
best_hits = pd.read_table("/Users/Farzaneh/Documents/phage-bacteria-interaction/GenoPHI/results/results_protein_family_coli_04_12_2025/strain/best_hits.tsv")

                 001-023_00001    NILS71_04345
0                001-023_00002       E20_03347
1                001-023_00003   ECOR-03_00361
2                001-023_00004       H27_03124
3                001-023_00005    NILS60_00069
4                001-023_00006    BCH953_00617
...                        ...             ...
1886764  e_coli_b_REL606_04412       E13_03303
1886765  e_coli_b_REL606_04413  E2348_69_04854
1886766  e_coli_b_REL606_04414        H4_04043
1886767  e_coli_b_REL606_04415     IAI62_02580
1886768  e_coli_b_REL606_04416     DEC2a_04737

[1886769 rows x 2 columns]

see if there are phages with none of phage features one.